from fastapi import APIRouter
from fastapi.responses import HTMLResponse, Response

router = APIRouter(tags=['dashboard-ui'])
UI_VERSION = '2026.08.17-4'

HTML = f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#07111f"><title>Phygital Bot</title><style>
*{{box-sizing:border-box}}html,body{{min-height:100%;margin:0}}body{{font-family:Inter,system-ui,sans-serif;background:#040814;color:#edf6ff;overflow-x:hidden}}body:before,body:after{{content:"";position:fixed;inset:-30%;z-index:-2;background:repeating-radial-gradient(ellipse at 50% 50%,rgba(31,168,255,.22) 0 2px,transparent 2px 24px);filter:blur(1px);animation:wave 15s linear infinite}}body:after{{background:repeating-radial-gradient(ellipse at 20% 80%,rgba(111,45,255,.18) 0 1px,transparent 1px 30px);animation-duration:22s;animation-direction:reverse;z-index:-3}}@keyframes wave{{0%{{transform:translate3d(-4%,-2%,0) scale(1)}}50%{{transform:translate3d(4%,3%,0) scale(1.08)}}100%{{transform:translate3d(-4%,-2%,0) scale(1)}}}}.spark{{position:fixed;inset:0;z-index:-1;pointer-events:none;background:linear-gradient(115deg,transparent 0 45%,rgba(62,190,255,.08) 48%,transparent 51% 100%);background-size:280% 100%;animation:spark 7s linear infinite}}@keyframes spark{{to{{background-position:-280% 0}}}}.w{{max-width:1240px;margin:auto;padding:28px 18px}}.card{{background:rgba(10,19,34,.82);border:1px solid rgba(92,168,255,.22);box-shadow:0 10px 40px rgba(0,0,0,.25),inset 0 0 30px rgba(30,120,255,.03);backdrop-filter:blur(14px);border-radius:18px;padding:18px;margin:14px 0}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px}}.two{{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:14px}}input,button,select,textarea{{width:100%;padding:11px 12px;margin:5px 0;border-radius:10px;border:1px solid #24466f;background:#08111f;color:#edf6ff}}button{{cursor:pointer;background:linear-gradient(180deg,#132b47,#0d1d31)}}button:hover{{border-color:#4cb6ff;box-shadow:0 0 18px rgba(76,182,255,.18)}}.nav{{display:flex;gap:8px;flex-wrap:wrap}}.nav button{{width:auto}}.h{{display:none!important}}.row{{padding:12px 0;border-bottom:1px solid rgba(130,180,230,.15)}}.badge{{display:inline-block;padding:3px 8px;border-radius:999px;background:#17314e;font-size:12px}}.muted{{color:#8fa8c3;font-size:13px}}.danger{{background:#351421;border-color:#6c263e}}.ok{{color:#79f0b3}}.err{{color:#ff9ea8;white-space:pre-wrap}}textarea{{min-height:220px;font-family:ui-monospace,monospace}}h1,h2,h3{{margin-top:8px}}.metric b{{font-size:24px}}.activity{{font-family:ui-monospace,monospace;font-size:13px}}.activity .who{{color:#74c8ff}}.activity .act{{color:#b9ffce}}
</style></head><body><div class="spark"></div><div class="w"><section id="login" class="card"><h1>Phygital Bot</h1><div class="muted">UI {UI_VERSION}</div><input id="u" autocomplete="username" placeholder="Usuario"><input id="p" autocomplete="current-password" type="password" placeholder="Contraseña"><button id="loginBtn" type="button">Entrar</button><div id="loginError" class="err"></div></section><section id="app" class="h"><h1>Dashboard</h1><div class="muted">UI {UI_VERSION}</div><div id="globalMsg" class="err"></div><div id="stats" class="grid"></div><div class="card nav"><button id="navHelp">Solicitudes</button><button id="navConv">Conversaciones</button><button id="navContacts">Contactos</button><button id="navCompanies">Empresas</button><button id="navUsers" class="h">Usuarios</button><button id="navActivity" class="h">Actividad</button><button id="logoutBtn">Salir</button></div><div id="content" class="card"></div></section></div><script src="/dashboard.js?v={UI_VERSION}"></script></body></html>'''

JS = r'''
(() => {
const TK='phygital_token', RK='phygital_role', $=id=>document.getElementById(id), admin=()=>localStorage.getItem(RK)==='admin';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const err=v=>{if($('globalMsg'))$('globalMsg').textContent=v||''};
const headers=()=>({Authorization:'Bearer '+(localStorage.getItem(TK)||'')});
async function api(path,opt={}){opt.headers={...(opt.headers||{}),...headers()};const r=await fetch(path,opt);if(r.status===401){localStorage.removeItem(TK);localStorage.removeItem(RK);location.reload();throw Error('Sesión expirada')}if(!r.ok){let t=await r.text();try{let j=JSON.parse(t);t=typeof j.detail==='string'?j.detail:JSON.stringify(j.detail)}catch(_){}throw Error(t||('HTTP '+r.status))}const ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
async function audit(action,el){try{await api('/api/audit/ui-events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,element_id:el?.id||null,label:(el?.textContent||'').trim().slice(0,160)||null,path:location.pathname})})}catch(_){}}
async function login(){const e=$('loginError');e.textContent='Conectando...';try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('u').value.trim(),password:$('p').value})});if(!r.ok){let m='Credenciales incorrectas';try{let j=await r.json();m=typeof j.detail==='string'?j.detail:m}catch(_){}e.textContent=m;return}const j=await r.json();localStorage.setItem(TK,j.access_token);localStorage.setItem(RK,j.rol);e.textContent='';show()}catch(x){e.textContent='No se pudo iniciar sesión: '+x.message}}
function logout(){audit('logout_click',$('logoutBtn'));localStorage.removeItem(TK);localStorage.removeItem(RK);location.reload()}
async function show(){$('login').classList.add('h');$('app').classList.remove('h');$('navUsers').classList.toggle('h',!admin());$('navActivity').classList.toggle('h',!admin());try{const s=await api('/api/stats');$('stats').innerHTML=Object.entries(s).map(([k,v])=>`<div class="card metric"><b>${esc(v)}</b><div>${esc(k)}</div></div>`).join('');help()}catch(x){err(x.message)}}
async function help(){err('');try{const a=await api('/api/help-requests');$('content').innerHTML='<h2>Solicitudes de ayuda</h2>'+a.map(r=>`<div class="row" data-help="${r.id}"><b>${esc(r.company_name)}</b> · ${esc(r.wa_user_id)}<div>${esc(r.body)}</div><span class="badge">${r.known_contact?'contacto':'no agregado'}</span> <span class="badge">${esc(r.status)}</span><div><button class="help-review">En revisión</button><button class="help-resolve">Resolver</button></div></div>`).join('');document.querySelectorAll('.help-review,.help-resolve').forEach(b=>b.addEventListener('click',async()=>{let row=b.closest('[data-help]'),status=b.classList.contains('help-resolve')?'resolved':'reviewing';try{await api('/api/help-requests/'+row.dataset.help,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});help()}catch(x){err(x.message)}}))}catch(x){err(x.message)}}
async function conv(){err('');try{const a=await api('/api/conversaciones');$('content').innerHTML='<h2>Conversaciones</h2>'+a.map(r=>`<div class="row"><b>${esc(r.company_name)}</b> · ${esc(r.wa_user_id)} <span class="badge">${r.known_contact?'contacto':'no agregado'}</span><div>${esc(r.state)} · ${esc(r.status)}</div></div>`).join('')}catch(x){err(x.message)}}
async function contacts(){err('');try{const a=await api('/api/contacts');$('content').innerHTML='<h2>Contactos autorizados</h2><p class="muted">Solo aparecen los contactos seleccionados desde la app Android.</p>'+a.map(r=>`<div class="row"><b>${esc(r.name||'Sin nombre')}</b><div>${esc(r.phone)}</div></div>`).join('')}catch(x){err(x.message)}}
async function users(){err('');try{const a=await api('/api/auth/usuarios');$('content').innerHTML=`<h2>Usuarios</h2><p class="muted">Tú eres el único administrador. Puedes crear, cambiar rol, desactivar, cambiar contraseña o eliminar usuarios secundarios.</p><div class="two"><div><h3>Crear usuario</h3><input id="nu" placeholder="Usuario"><input id="np" type="password" placeholder="Contraseña (mín. 8)"><select id="nr"><option value="operador">Operador</option><option value="lector">Lector</option></select><button id="createUserBtn">Crear usuario</button></div><div><h3>Usuarios existentes</h3><div id="ul"></div></div></div>`;$('ul').innerHTML=a.map(u=>`<div class="row" data-uid="${u.id}"><b>${esc(u.username)}</b> <span class="badge">${esc(u.role)}</span>${u.is_primary_admin?' <span class="badge">administrador principal</span>':''}<div>${u.is_active?'Activo':'Desactivado'}</div>${u.is_primary_admin?'':`<select class="roleEdit"><option value="operador" ${u.role==='operador'?'selected':''}>Operador</option><option value="lector" ${u.role==='lector'?'selected':''}>Lector</option></select><button class="saveRole">Guardar rol</button><button class="toggleUser">${u.is_active?'Desactivar':'Activar'}</button><button class="resetUser">Cambiar contraseña</button><button class="deleteUser danger">Eliminar usuario</button>`}</div>`).join('');$('createUserBtn').onclick=async()=>{try{await api('/api/auth/crear-usuario',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('nu').value.trim(),password:$('np').value,role:$('nr').value})});users()}catch(x){err(x.message)}};document.querySelectorAll('[data-uid]').forEach(row=>{let id=row.dataset.uid,role=row.querySelector('.roleEdit');let save=row.querySelector('.saveRole');if(save)save.onclick=async()=>{try{await api('/api/auth/usuarios/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:role.value})});users()}catch(x){err(x.message)}};let tog=row.querySelector('.toggleUser');if(tog)tog.onclick=async()=>{let active=tog.textContent==='Activar';try{await api('/api/auth/usuarios/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_active:active})});users()}catch(x){err(x.message)}};let rst=row.querySelector('.resetUser');if(rst)rst.onclick=async()=>{let pw=prompt('Nueva contraseña (mínimo 8 caracteres)');if(!pw)return;try{await api('/api/auth/usuarios/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:pw})});alert('Contraseña actualizada')}catch(x){err(x.message)}};let del=row.querySelector('.deleteUser');if(del)del.onclick=async()=>{if(!confirm('¿Eliminar este usuario definitivamente?'))return;try{await api('/api/auth/usuarios/'+id,{method:'DELETE'});users()}catch(x){err(x.message)}}})}catch(x){err(x.message)}}
async function activity(){err('');try{const rows=await api('/api/audit/activity?limit=300');$('content').innerHTML='<h2>Actividad de usuarios</h2><p class="muted">Se registran accesos, navegación y acciones importantes. No se guardan contraseñas ni contenido de campos sensibles.</p>'+rows.map(r=>`<div class="row activity"><span class="who">${esc(r.username||'sistema')}</span> · <span class="act">${esc(r.action)}</span> · ${esc(r.entity||'')} ${r.entity_id?'#'+esc(r.entity_id):''}<div class="muted">${esc(r.created_at)} · ${esc(JSON.stringify(r.details||{}))}</div></div>`).join('')}catch(x){err(x.message)}}
async function companies(){err('');try{const a=await api('/api/empresas/listar');$('content').innerHTML=`<h2>Empresas</h2>${admin()?'<div><input id="ck" placeholder="Clave"><input id="cn" placeholder="Nombre"><button id="createCompany">Crear empresa</button></div>':''}<div id="companiesList"></div>`;$('companiesList').innerHTML=a.map(c=>`<div class="row"><b>${esc(c.nombre)}</b> <span class="badge">${c.activa?'activa':'inactiva'}</span><div class="muted">${esc(c.empresa_id)}</div></div>`).join('');if($('createCompany'))$('createCompany').onclick=async()=>{try{await api('/api/empresas/crear',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({company_key:$('ck').value.trim(),name:$('cn').value.trim(),stores:[],whatsapp_numbers:[],phone_number_ids:[]})});companies()}catch(x){err(x.message)}}}catch(x){err(x.message)}}
document.addEventListener('DOMContentLoaded',()=>{$('loginBtn').onclick=login;$('p').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('navHelp').onclick=help;$('navConv').onclick=conv;$('navContacts').onclick=contacts;$('navCompanies').onclick=companies;$('navUsers').onclick=users;$('navActivity').onclick=activity;$('logoutBtn').onclick=logout;document.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&localStorage.getItem(TK)&&b.id!=='loginBtn')audit('ui_click',b)});if(localStorage.getItem(TK))show()});
})();
'''

@router.get('/dashboard', response_class=HTMLResponse)
def dashboard(): return HTML

@router.get('/dashboard.js')
def dashboard_js(): return Response(JS, media_type='application/javascript', headers={'Cache-Control':'no-store'})

@router.get('/manifest.webmanifest')
def manifest(): return {'name':'Phygital Bot Dashboard','short_name':'Phygital Bot','start_url':'/dashboard','display':'standalone','background_color':'#040814','theme_color':'#07111f'}

@router.get('/sw.js')
def sw(): return Response("self.addEventListener('fetch',()=>{})", media_type='application/javascript', headers={'Cache-Control':'no-store'})
