from fastapi import APIRouter
from fastapi.responses import HTMLResponse, Response

from .dashboard_ai_neural_patch import _html as base_html, _js as base_js

router = APIRouter(tags=['dashboard-ui-ai-neural-entry'])
UI_VERSION = '2026.09.04-73'


def _html() -> str:
    html = base_html()
    html = html.replace('UI 2026.09.04-68', f'UI {UI_VERSION}')
    html = html.replace('/dashboard.js?v=2026.09.04-68', f'/dashboard.js?v={UI_VERSION}')
    html = html.replace('</head>', '''<style id="prototypeVisualRefresh">
:root{--dash-bg:#06111f;--dash-bg2:#07192b;--dash-bg3:#05101b;--dash-panel:#0b1d31;--dash-panel2:#0f2843;--dash-line:#1c3b59;--dash-text:#eef6ff;--dash-muted:#8eacc8;--dash-blue:#2196ff;--dash-green:#18c788;--dash-red:#ff526d;--dash-purple:#8b5cf6;--dash-amber:#f2b940;--dash-shadow:0 18px 50px rgba(0,0,0,.28)}
html,body{background:linear-gradient(135deg,var(--dash-bg),var(--dash-bg2) 50%,var(--dash-bg3))!important;color:var(--dash-text)!important;font-family:Inter,Segoe UI,Arial,sans-serif}
body:before{content:'';position:fixed;inset:0;background:radial-gradient(circle at 0 0,rgba(33,150,255,.09),transparent 28%),radial-gradient(circle at 100% 0,rgba(139,92,246,.07),transparent 23%);pointer-events:none;z-index:-1}.w{max-width:1580px!important}.ps-side{background:#071629!important;border-right:1px solid #0c2a45!important}.ps-brand{color:#fff!important}.ps-side .nav button{color:#c7dcf1!important}.ps-side .nav button:hover,.ps-side .nav button.ps-active{background:#0d3159!important;color:#fff!important;border-color:#1f5683!important}.ps-search{background:#0a1c2f!important;border-color:#1a446b!important;color:#dcecf8!important}.ps-main{background:transparent!important}.card,#content.card,#content .card{background:linear-gradient(180deg,rgba(16,42,69,.92),rgba(8,25,42,.96))!important;border:1px solid var(--dash-line)!important;border-radius:15px!important;box-shadow:var(--dash-shadow)!important}.muted,.ps-role-title,.ps-scope{color:var(--dash-muted)!important}input,select,textarea{background:#061827!important;border:1px solid #2b587f!important;color:#fff!important;border-radius:10px!important}button{border-radius:10px!important}#content button,.ps-main button{background:#0b2945!important;border:1px solid #24537c!important;color:#dcecf8!important}#content button:hover,.ps-main button:hover{border-color:#46a0ff!important;box-shadow:0 8px 22px rgba(33,150,255,.12)!important}.danger{background:#3a1830!important;border-color:#8f3455!important;color:#ffdce4!important}.badge{background:#17314e!important;border:1px solid #2c5d86!important;color:#dceeff!important}
#stats{display:grid!important;grid-template-columns:repeat(auto-fit,minmax(205px,1fr))!important;gap:12px!important;margin:16px 0 18px!important}#stats>.card{margin:0!important;min-height:96px!important;padding:15px!important}.dash-metric{display:flex;align-items:center;gap:13px}.dash-metric-icon{width:46px;height:46px;min-width:46px;border-radius:12px;display:grid;place-items:center;font-size:22px;background:linear-gradient(145deg,#2ea7ff,#1458d8)}.dash-metric-icon.green{background:linear-gradient(145deg,#27d797,#0d7654)}.dash-metric-icon.purple{background:linear-gradient(145deg,#9d77ff,#5947c7)}.dash-metric-icon.amber{background:linear-gradient(145deg,#f6ca60,#cb8e1a)}.dash-metric-icon.red{background:linear-gradient(145deg,#ff7b90,#cf3857)}.dash-metric-label{font-size:13px;color:#cfe2f3}.dash-metric-value{font-size:27px;font-weight:800;line-height:1.1}.dash-metric-note{font-size:11px;color:var(--dash-muted);margin-top:4px}
.dash-overview{margin:0 0 16px}.dash-overview-head{display:flex;justify-content:space-between;align-items:end;gap:14px;flex-wrap:wrap;margin-bottom:12px}.dash-overview-head h2{margin:0;font-size:27px}.dash-overview-head p{margin:5px 0 0;color:var(--dash-muted)}.dash-overview-tag{font-size:12px;color:#9db7d1}.dash-charts{display:grid;grid-template-columns:1.2fr .9fr 1fr;gap:12px}.dash-chart{padding:14px}.dash-chart-title{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:10px}.dash-chart-title h3{margin:0;font-size:17px}.dash-chart-title span{font-size:11px;color:var(--dash-muted)}.dash-line{height:205px;border-left:1px solid #2a4d6a;border-bottom:1px solid #2a4d6a;margin:12px 8px 8px}.dash-line svg{width:100%;height:100%;overflow:visible}.dash-donut-wrap{display:grid;grid-template-columns:150px 1fr;align-items:center;gap:10px}.dash-donut{width:140px;height:140px;border-radius:50%;position:relative;margin:auto}.dash-donut:after{content:attr(data-total) '\A Total';white-space:pre;position:absolute;inset:31px;border-radius:50%;background:#0b1d31;display:grid;place-items:center;text-align:center;font-weight:700;line-height:1.2}.dash-legend div{font-size:12px;color:#cde0ef;margin:8px 0}.dash-legend i{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:8px}.dash-bars{height:170px;display:flex;align-items:end;gap:12px;padding:18px 4px 0}.dash-bar-wrap{flex:1;display:flex;flex-direction:column;align-items:center;gap:6px}.dash-bar{width:100%;max-width:48px;border-radius:7px 7px 0 0;background:linear-gradient(#4b9aff,#176bd1);min-height:18px}.dash-bar-wrap b{font-size:11px}.dash-bar-wrap span{font-size:10px;color:#b7cee1;text-align:center}.dash-quick{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.dash-action{padding:13px;border-radius:12px;border:1px solid #214a6d;background:#0b2340}.dash-action.red{background:#3a1830;border-color:#8f3455}.dash-action.green{background:#0c473f;border-color:#147864}.dash-action.purple{background:#2e2360;border-color:#5d49a8}.dash-action.blue{background:#0d3764;border-color:#1a66b7}.dash-action b{display:block}.dash-action span{font-size:11px;color:#bcd0e1}.row{border-color:#173854!important}#content th{background:#0c2b47!important;color:#a9c5dc!important}#content td{border-bottom-color:#173854!important;color:#dceaf7!important}.bubble.in{background:#102842!important;border:1px solid #234864!important}.bubble.out{background:#113423!important;border:1px solid #1e6c54!important}
@media(max-width:1200px){.dash-charts{grid-template-columns:1fr}.dash-quick{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){.dash-overview-head h2{font-size:23px}.dash-donut-wrap{grid-template-columns:1fr}.dash-quick{grid-template-columns:1fr}#stats{grid-template-columns:1fr!important}}
</style></head>''')
    return html


def _js() -> str:
    js = base_js()
    patch = r'''
psIsSuperAdmin=function(){const u=USER_ACCESS||{};return String(u.role||'').toLowerCase()==='admin'};
function forceAdminAiEntry(){if(!psIsSuperAdmin())return;installSuperAdminAiNav();const b=document.getElementById('navAINeural');if(b){b.classList.remove('h','ps-permission-hidden');b.style.display=''}}
function dashMetricMeta(key){const k=String(key||'').toLowerCase();if(k.includes('empresa'))return ['🏬','purple','Empresas visibles'];if(k.includes('mensaje'))return ['✉️','green','Mensajes registrados'];if(k.includes('solic'))return ['🎫','amber','Solicitudes activas'];if(k.includes('ticket'))return ['🧾','amber','Seguimiento de casos'];if(k.includes('convers'))return ['💬','blue','Conversaciones'];if(k.includes('usuario'))return ['🛡️','purple','Usuarios activos'];if(k.includes('contact'))return ['👥','blue','Contactos'];return ['📊','red','Indicador del sistema']}
function dashLabel(k){return String(k||'').replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}
function renderDashStats(s){window.__dashStats=s||{};return Object.entries(s||{}).map(([k,v])=>{const m=dashMetricMeta(k);return `<div class="card dash-metric"><div class="dash-metric-icon ${m[1]}">${m[0]}</div><div><div class="dash-metric-label">${esc(dashLabel(k))}</div><div class="dash-metric-value">${esc(v)}</div><div class="dash-metric-note">${esc(m[2])}</div></div></div>`}).join('')}
function dashNumeric(){const a=Object.entries(window.__dashStats||{}).filter(([,v])=>Number.isFinite(Number(v)));return a.length?a:[['empresas',0],['conversaciones',0],['mensajes',0],['solicitudes',0]]}
function dashLineSvg(){const raw=dashNumeric().map(([,v])=>Math.max(0,Number(v)||0)),vals=[];while(vals.length<8){const n=raw[vals.length%raw.length]||0;vals.push(Math.max(1,n+((vals.length%3)*2)+(vals.length%2?3:0)))}const max=Math.max(...vals,1),min=Math.min(...vals,0),span=Math.max(1,max-min),left=15,right=590,top=22,bottom=180,step=(right-left)/(vals.length-1);const pts=vals.map((v,i)=>({x:left+i*step,y:bottom-((v-min)/span)*(bottom-top)}));const poly=pts.map(p=>`${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' '),fill=poly+` ${right},${bottom} ${left},${bottom}`;return `<svg viewBox="0 0 600 210" preserveAspectRatio="none"><polygon points="${fill}" fill="rgba(70,160,255,.14)"></polygon><polyline points="${poly}" fill="none" stroke="#46a0ff" stroke-width="4"></polyline><g fill="#8bc3ff">${pts.map(p=>`<circle cx="${p.x.toFixed(1)}" cy="${p.y.toFixed(1)}" r="5"></circle>`).join('')}</g></svg>`}
function dashDonut(){const colors=['#ff526d','#377fe8','#8b5cf6','#18c788'],a=dashNumeric().slice(0,4),total=a.reduce((x,[,v])=>x+(Number(v)||0),0)||1;let pos=0;const seg=a.map(([k,v],i)=>{const n=Math.max(0,Number(v)||0),pct=n*100/total,start=pos,end=pos+pct;pos=end;return {label:dashLabel(k),value:n,color:colors[i%colors.length],start,end}});return {total,seg,gradient:'conic-gradient('+seg.map(x=>`${x.color} ${x.start.toFixed(1)}% ${x.end.toFixed(1)}%`).join(',')+')'}}
function dashBars(){const a=dashNumeric().slice(0,5),max=Math.max(...a.map(([,v])=>Number(v)||0),1);return a.map(([k,v])=>{const n=Math.max(0,Number(v)||0),h=Math.max(18,Math.round(n*125/max));return `<div class="dash-bar-wrap"><div class="dash-bar" style="height:${h}px"></div><b>${esc(n)}</b><span>${esc(dashLabel(k))}</span></div>`}).join('')}
function dashCurrentCompany(){try{return COMPANY_CONTEXT?.name||'Todas las empresas'}catch(_){return 'Todas las empresas'}}
function dashViewTitle(){const v=typeof LIVE_VIEW!=='undefined'?LIVE_VIEW:'';if(v==='conv')return ['Conversaciones','Casos que ya requieren o reciben atención humana.'];if(v==='companies')return ['Empresas y flujos','Configuración de empresas, tiendas y árboles de atención.'];if(v==='tickets')return ['Tickets','Seguimiento del estado y trazabilidad de los casos.'];if(v==='reports')return ['Reportes','Indicadores operativos y desempeño del soporte.'];if(v==='users')return ['Usuarios y permisos','Accesos por rol, empresa y responsabilidad.'];if(v==='activity')return ['Actividad','Cambios y movimientos registrados en el sistema.'];return ['Centro de operación','Monitorea solicitudes, conversaciones, tickets y métricas clave.']}
function renderDashOverview(){const d=dashDonut(),title=dashViewTitle(),company=dashCurrentCompany();return `<section id="dashOverview" class="dash-overview"><div class="dash-overview-head"><div><h2>${esc(title[0])}</h2><p>${esc(title[1])}</p></div><div class="dash-overview-tag">${esc(company)} · visual inspirado en tus prototipos</div></div><div class="dash-quick"><div class="dash-action blue"><b>💬 Solicitudes</b><span>Entrada y atención inicial del bot</span></div><div class="dash-action green"><b>🎧 Conversaciones</b><span>Casos escalados a humano</span></div><div class="dash-action purple"><b>👥 Usuarios</b><span>Permisos y operación por rol</span></div><div class="dash-action red"><b>🧠 IA · Aprendizaje</b><span>Entrenamiento y conocimiento aprobado</span></div></div><div class="dash-charts"><div class="card dash-chart"><div class="dash-chart-title"><h3>Comportamiento general</h3><span>Métricas actuales</span></div><div class="dash-line">${dashLineSvg()}</div></div><div class="card dash-chart"><div class="dash-chart-title"><h3>Distribución</h3><span>Indicadores visibles</span></div><div class="dash-donut-wrap"><div class="dash-donut" data-total="${esc(d.total)}" style="background:${d.gradient}"></div><div class="dash-legend">${d.seg.map(x=>`<div><i style="background:${x.color}"></i>${esc(x.label)} · ${esc(x.value)}</div>`).join('')}</div></div></div><div class="card dash-chart"><div class="dash-chart-title"><h3>Comparativo</h3><span>Escala relativa</span></div><div class="dash-bars">${dashBars()}</div></div></div></section>`}
function decorateDashboardView(){const content=$('content');if(!content)return;const v=typeof LIVE_VIEW!=='undefined'?LIVE_VIEW:'';if(['chat','ai','appearance','role'].includes(v))return;document.getElementById('dashOverview')?.remove();content.insertAdjacentHTML('afterbegin',renderDashOverview())}
const _entryRefresh=psRefreshRoleChrome;psRefreshRoleChrome=function(){_entryRefresh();forceAdminAiEntry()};
const _entryApplyPermissions=applyPermissionNavigation;applyPermissionNavigation=function(){_entryApplyPermissions();forceAdminAiEntry()};
const _entryShow=show;let _dashboardInitialShowDone=false;show=async function(){if(!_dashboardInitialShowDone){_dashboardInitialShowDone=true;await _entryShow();try{const s=await api('/api/stats');const stats=$('stats');if(stats)stats.innerHTML=renderDashStats(s)}catch(_){}setTimeout(()=>{forceAdminAiEntry();decorateDashboardView()},0);return}try{if(typeof loadMyAccess==='function')await loadMyAccess();const s=await api('/api/stats');const stats=$('stats');if(stats)stats.innerHTML=renderDashStats(s);if(typeof loadCompanyContext==='function')await loadCompanyContext();if(typeof psRefreshRoleChrome==='function')psRefreshRoleChrome();setTimeout(()=>{forceAdminAiEntry();decorateDashboardView()},0)}catch(x){err(x.message)}};
function rememberDashboardView(name){try{sessionStorage.setItem('phygital_dashboard_view_v1',name||'help')}catch(_){}}
const _entryHelp=help;help=async function(...args){rememberDashboardView('help');const r=await _entryHelp(...args);setTimeout(decorateDashboardView,0);return r};
const _entryConv=conv;conv=async function(...args){rememberDashboardView('conv');const r=await _entryConv(...args);setTimeout(decorateDashboardView,0);return r};
const _entryCompanies=companies;companies=async function(...args){rememberDashboardView('companies');const r=await _entryCompanies(...args);setTimeout(decorateDashboardView,0);return r};
if(typeof ticketsView==='function'){const f=ticketsView;ticketsView=async function(...args){rememberDashboardView('tickets');const r=await f(...args);setTimeout(decorateDashboardView,0);return r}}
if(typeof reportsView==='function'){const f=reportsView;reportsView=async function(...args){rememberDashboardView('reports');const r=await f(...args);setTimeout(decorateDashboardView,0);return r}}
if(typeof users==='function'){const f=users;users=async function(...args){rememberDashboardView('users');const r=await f(...args);setTimeout(decorateDashboardView,0);return r}}
if(typeof activity==='function'){const f=activity;activity=async function(...args){rememberDashboardView('activity');const r=await f(...args);setTimeout(decorateDashboardView,0);return r}}
const _entryRenderAi=renderSuperAdminAiNeural;renderSuperAdminAiNeural=async function(...args){if(typeof LIVE_VIEW!=='undefined')LIVE_VIEW='ai';if(typeof LIVE_CHAT_ID!=='undefined')LIVE_CHAT_ID=null;rememberDashboardView('ai');const out=await _entryRenderAi(...args);try{const s=await api('/api/admin-ai/status');const badge=document.querySelector('.ai-ai-badge');if(badge){const labels={openai:'OpenAI',ollama:'Modelo local',retrieval:'Memoria local'};badge.textContent=`● ${labels[s.provider]||s.provider||'IA local'} · ${s.model||'sin modelo'}`}}catch(_){}return out};
const _entryLiveRefresh=typeof liveRefresh==='function'?liveRefresh:null;if(_entryLiveRefresh){liveRefresh=async function(){if(typeof LIVE_VIEW!=='undefined'&&LIVE_VIEW==='ai'){if(LIVE_REFRESH_BUSY||!localStorage.getItem(TK)||$('app')?.classList.contains('h'))return;LIVE_REFRESH_BUSY=true;try{if(typeof liveStats==='function')await liveStats();forceAdminAiEntry()}catch(_){}finally{LIVE_REFRESH_BUSY=false}return}const out=await _entryLiveRefresh();try{const s=await api('/api/stats');const stats=$('stats');if(stats)stats.innerHTML=renderDashStats(s);decorateDashboardView()}catch(_){}return out}};
let _aiEntryAttempts=0;const _aiEntryTimer=setInterval(()=>{forceAdminAiEntry();_aiEntryAttempts+=1;if(document.getElementById('navAINeural')||_aiEntryAttempts>20)clearInterval(_aiEntryTimer)},250);document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{forceAdminAiEntry();decorateDashboardView()},50));
'''
    marker='\n})();'
    if marker in js:
        head, tail = js.rsplit(marker, 1)
        return head + '\n' + patch + marker + tail
    return js + '\n' + patch


@router.get('/dashboard', response_class=HTMLResponse)
def dashboard_ai_neural_entry():
    return _html()


@router.get('/dashboard.js')
def dashboard_ai_neural_entry_js():
    return Response(_js(), media_type='application/javascript', headers={'Cache-Control':'public, max-age=31536000, immutable'})
