from fastapi import APIRouter
from fastapi.responses import HTMLResponse, Response

router = APIRouter(tags=['dashboard-ui'])

HTML = '''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#101318"><link rel="manifest" href="/manifest.webmanifest"><title>Phygital Bot</title><style>body{font-family:system-ui;background:#0b0e12;color:#eef2f7;margin:0}.w{max-width:1180px;margin:auto;padding:16px}.c{background:#151a21;border:1px solid #26303b;border-radius:14px;padding:16px;margin:12px 0}.g{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.two{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}input,button,select,textarea{box-sizing:border-box;width:100%;padding:11px;margin:5px 0;border-radius:9px;border:1px solid #354052;background:#0f141a;color:#eef2f7}button{cursor:pointer;background:#202936}.nav{display:flex;gap:8px;flex-wrap:wrap}.nav button{width:auto}.h{display:none}.row{padding:10px 0;border-bottom:1px solid #26303b}.b{display:inline-block;padding:3px 8px;background:#26303b;border-radius:999px;font-size:12px}.muted{color:#9ba8b6;font-size:13px}textarea{min-height:240px;font-family:monospace}.danger{background:#402020}.ok{color:#75d69c}</style></head><body><div class="w"><section id="login" class="c"><h1>Phygital Bot</h1><input id="u" placeholder="Usuario"><input id="p" type="password" placeholder="Contraseña"><button onclick="go()">Entrar</button><div id="e"></div></section><section id="app" class="h"><h1>Dashboard</h1><div id="stats" class="g"></div><div class="c nav"><button onclick="help()">Solicitudes</button><button onclick="conv()">Conversaciones</button><button onclick="contacts()">Contactos</button><button onclick="companies()">Empresas</button><button id="usersBtn" class="h" onclick="users()">Usuarios</button></div><div id="content" class="c"></div></section></div><script>
const k='phygital_token', rk='phygital_role', byId=id=>document.getElementById(id), h=()=>({'Authorization':'Bearer '+localStorage.getItem(k)});
async function go(){const error=byId('e');error.textContent='';try{let r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:byId('u').value,password:byId('p').value})});if(!r.ok){error.textContent='Credenciales incorrectas';return}let j=await r.json();localStorage.setItem(k,j.access_token);localStorage.setItem(rk,j.rol);await show()}catch(err){error.textContent='No se pudo iniciar sesión: '+err.message}}
async function api(x,opt={}){opt.headers={...(opt.headers||{}),...h()};let r=await fetch(x,opt);if(r.status===401){localStorage.removeItem(k);localStorage.removeItem(rk);location.reload();throw Error('Sesión expirada')}if(!r.ok){let t=await r.text();throw Error(t)}let ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
async function show(){byId('login').classList.add('h');byId('app').classList.remove('h');if(localStorage.getItem(rk)==='admin')byId('usersBtn').classList.remove('h');let s=await api('/api/stats');byId('stats').innerHTML=Object.entries(s).map(x=>'<div class="c"><b>'+x[1]+'</b><div>'+x[0]+'</div></div>').join('');help()}
async function help(){let a=await api('/api/help-requests');byId('content').innerHTML='<h2>Solicitudes de ayuda</h2>'+a.map(r=>'<div class="row"><b>'+r.company_name+'</b> · '+r.wa_user_id+'<div>'+esc(r.body)+'</div><span class="b">'+(r.known_contact?'contacto':'no agregado')+'</span> <span class="b">'+r.status+'</span></div>').join('')}
async function conv(){let a=await api('/api/conversaciones');byId('content').innerHTML='<h2>Conversaciones</h2>'+a.map(r=>'<div class="row"><b>'+r.company_name+'</b> · '+r.wa_user_id+' <span class="b">'+(r.known_contact?'contacto':'no agregado')+'</span><div>'+r.state+' · '+r.status+'</div></div>').join('')}
async function contacts(){let a=await api('/api/contacts');byId('content').innerHTML='<h2>Contactos autorizados</h2><p class="muted">Solo aparecen los contactos que tú seleccionaste desde la app Android.</p>'+a.map(r=>'<div class="row"><b>'+esc(r.name||'Sin nombre')+'</b><div>'+r.phone+'</div></div>').join('')}
async function users(){let a=await api('/api/auth/usuarios');byId('content').innerHTML='<h2>Usuarios</h2><p class="muted">Solo el administrador principal puede gestionar usuarios. Los usuarios extra nunca pueden convertirse en administradores.</p><div class="two"><div><h3>Crear usuario</h3><input id="nu" placeholder="Usuario"><input id="np" type="password" placeholder="Contraseña (mín. 8)"><select id="nr"><option value="operador">Operador</option><option value="lector">Lector</option></select><button onclick="createUser()">Crear usuario</button></div><div><h3>Usuarios existentes</h3>'+a.map(x=>'<div class="row"><b>'+esc(x.username)+'</b> <span class="b">'+x.role+'</span> '+(x.is_primary_admin?'<span class="b">administrador principal</span>':'')+'<div>'+(x.is_active?'Activo':'Desactivado')+'</div>'+(!x.is_primary_admin?'<button onclick="toggleUser('+x.id+','+(!x.is_active)+')">'+(x.is_active?'Desactivar':'Activar')+'</button><button onclick="resetUser('+x.id+')">Cambiar contraseña</button>':'')+'</div>').join('')+'</div></div>'}
async function createUser(){try{await api('/api/auth/crear-usuario',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:byId('nu').value,password:byId('np').value,role:byId('nr').value})});users()}catch(err){alert(err.message)}}
async function toggleUser(id,v){await api('/api/auth/usuarios/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_active:v})});users()}
async function resetUser(id){let p2=prompt('Nueva contraseña (mínimo 8 caracteres)');if(!p2)return;await api('/api/auth/usuarios/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:p2})});alert('Contraseña actualizada')}
async function companies(){let a=await api('/api/empresas/listar');byId('content').innerHTML='<h2>Empresas</h2><div class="two"><div><h3>Nueva empresa</h3><input id="ck" placeholder="Clave, ej. cliente_norte"><input id="cn" placeholder="Nombre"><button onclick="createCompany()">Crear empresa</button></div><div><h3>Administrar</h3><div id="clist">'+a.map(c=>'<button onclick="companyPanel(\''+c.empresa_id+'\')">'+esc(c.nombre)+(c.activa?'':' (inactiva)')+'</button>').join('')+'</div></div></div>'}
async function createCompany(){try{await api('/api/empresas/crear',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({company_key:byId('ck').value,name:byId('cn').value,stores:[],whatsapp_numbers:[],phone_number_ids:[]})});companies()}catch(err){alert(err.message)}}
async function companyPanel(key){let all=await api('/api/empresas/listar'),c=all.find(x=>x.empresa_id===key);let sup=await api('/api/empresas/'+key+'/soporte');let files=await api('/api/empresas/'+key+'/archivos');let tree=await api('/api/empresas/'+key+'/arbol');byId('content').innerHTML='<button onclick="companies()">← Empresas</button><h2>'+esc(c.nombre)+'</h2><div class="two"><div class="c"><h3>Configuración</h3><input id="ename" value="'+attr(c.nombre)+'"><button onclick="renameCompany(\''+key+'\')">Guardar nombre</button><button class="danger" onclick="toggleCompany(\''+key+'\','+(!c.activa)+')">'+(c.activa?'Desactivar':'Activar')+'</button><p class="muted">Clave: '+key+'</p></div><div class="c"><h3>Soporte y escalamiento</h3><input id="sname" placeholder="Nombre"><input id="sphone" placeholder="Teléfono"><select id="srole"><option value="primary">Primario</option><option value="secondary">Secundario</option></select><input id="smins" type="number" value="15" min="1"><button onclick="addSupport(\''+key+'\')">Agregar apoyo</button><div>'+sup.map(s=>'<div class="row"><b>'+esc(s.name)+'</b> '+s.phone+' <span class="b">'+s.role+'</span><div>Escala tras '+s.escalation_after_minutes+' min</div><button class="danger" onclick="delSupport(\''+key+'\','+s.id+')">Quitar</button></div>').join('')+'</div></div></div><div class="two"><div class="c"><h3>Árbol de decisiones</h3><p class="muted">Editor JSON inicial. La siguiente versión será visual por bloques.</p><textarea id="tree">'+esc(JSON.stringify(tree,null,2))+'</textarea><button onclick="saveTree(\''+key+'\')">Guardar árbol</button></div><div class="c"><h3>Archivos de la empresa</h3><input id="fdesc" placeholder="Descripción"><input id="fup" type="file"><button onclick="uploadFile(\''+key+'\')">Subir archivo</button><div>'+files.map(f=>'<div class="row"><b>'+esc(f.filename)+'</b><div>'+Math.round(f.size_bytes/1024)+' KB</div><button onclick="downloadFile(\''+key+'\','+f.id+',\''+js(f.filename)+'\')">Descargar</button><button class="danger" onclick="deleteFile(\''+key+'\','+f.id+')">Eliminar</button></div>').join('')+'</div></div></div><div class="c"><h3>Chats por empresa</h3><button onclick="companyChats('+c.id+')">Ver conversaciones de '+esc(c.nombre)+'</button></div>'}
async function renameCompany(k2){await api('/api/empresas/'+k2,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:byId('ename').value})});companyPanel(k2)}
async function toggleCompany(k2,v){await api('/api/empresas/'+k2,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_active:v})});companyPanel(k2)}
async function saveTree(k2){try{let obj=JSON.parse(byId('tree').value);await api('/api/empresas/'+k2+'/arbol',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({structure:obj})});alert('Árbol guardado')}catch(err){alert('JSON inválido o error: '+err.message)}}
async function addSupport(k2){await api('/api/empresas/'+k2+'/soporte',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:byId('sname').value,phone:byId('sphone').value,role:byId('srole').value,priority:1,escalation_after_minutes:Number(byId('smins').value||15)})});companyPanel(k2)}
async function delSupport(k2,id){await api('/api/empresas/'+k2+'/soporte/'+id,{method:'DELETE'});companyPanel(k2)}
async function uploadFile(k2){let f=byId('fup').files[0];if(!f){alert('Selecciona un archivo');return}let fd=new FormData();fd.append('file',f);fd.append('description',byId('fdesc').value);await api('/api/empresas/'+k2+'/archivos',{method:'POST',body:fd});companyPanel(k2)}
async function downloadFile(k2,id,name){let r=await fetch('/api/empresas/'+k2+'/archivos/'+id+'/descargar',{headers:h()});if(!r.ok){alert('No se pudo descargar');return}let b=await r.blob(),u2=URL.createObjectURL(b),a=document.createElement('a');a.href=u2;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u2)}
async function deleteFile(k2,id){await api('/api/empresas/'+k2+'/archivos/'+id,{method:'DELETE'});companyPanel(k2)}
async function companyChats(id){let a=await api('/api/conversaciones?company_id='+id);byId('content').innerHTML='<button onclick="companies()">← Empresas</button><h2>Conversaciones</h2>'+a.map(r=>'<div class="row"><b>'+r.wa_user_id+'</b><div>'+r.state+' · '+r.status+'</div></div>').join('')}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function attr(v){return esc(v)}function js(v){return String(v||'').replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');if(localStorage.getItem(k))show();
</script></body></html>'''

@router.get('/dashboard', response_class=HTMLResponse)
def dashboard(): return HTML

@router.get('/manifest.webmanifest')
def manifest(): return {'name':'Phygital Bot Dashboard','short_name':'Phygital Bot','start_url':'/dashboard','display':'standalone','background_color':'#0b0e12','theme_color':'#101318'}

@router.get('/sw.js')
def sw(): return Response("self.addEventListener('fetch',()=>{})", media_type='application/javascript')
